# Generated by Django 5.0.1 on 2024-02-04 06:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mcqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False)),
                ('question', models.CharField(max_length=1000)),
                ('option_A', models.CharField(max_length=100)),
                ('option_B', models.CharField(max_length=100)),
                ('option_C', models.CharField(max_length=100)),
                ('option_D', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=50)),
                ('data_resgister', models.DateTimeField(default=datetime.datetime(2024, 2, 4, 12, 12, 13, 998246))),
            ],
        ),
        migrations.CreateModel(
            name='user_output',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id', serialize=False, to='_api.users')),
                ('total_score', models.IntegerField()),
                ('Completion_time', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='_api.users')),
            ],
        ),
    ]
