# Generated by Django 4.2.9 on 2024-01-17 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqs',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 12, 9, 25, 451057)),
        ),
    ]
