# Generated by Django 5.0.1 on 2024-02-04 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_output',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_output',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 12, 20, 56, 328693)),
        ),
    ]
