# Generated by Django 4.2.9 on 2024-01-17 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0002_alter_mcqs_number_alter_users_data_resgister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 12, 19, 48, 716730)),
        ),
    ]
