# Generated by Django 4.2.7 on 2024-01-18 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0003_alter_users_data_resgister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 22, 0, 456942)),
        ),
    ]
