# Generated by Django 5.0.1 on 2024-01-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0005_alter_users_data_resgister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
