# Generated by Django 5.0.1 on 2024-01-24 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0006_alter_users_data_resgister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_resgister',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 20, 15, 35, 316603)),
        ),
    ]
